#!/bin/sh
set -e -u -x
cp -r tests/ "$ADTTMP"
cd "$ADTTMP/tests/"
export PYTHONWARNINGS=d
for py in $(py3versions -i); do
  # text mode file opening is locale dependent so try both ASCII and UTF-8
  LC_ALL=C $py /usr/bin/nosetests3 --verbose --exe
  LC_ALL=C.UTF-8 $py /usr/bin/nosetests3 --verbose --exe
done
