#!/bin/sh
set -e -u -x
cp -r tests/ "$ADTTMP"
cd "$ADTTMP/tests/"
export PYTHONWARNINGS=d
# test suite requires python2.7
LC_ALL=C python2.7 /usr/bin/nosetests --verbose --exe
LC_ALL=C.UTF-8 python2.7 /usr/bin/nosetests --verbose --exe
